apiVersion: v1
kind: Namespace
metadata:
  name: shared
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clamav
  namespace: shared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clamav
  template:
    metadata:
      labels:
        app: clamav
    spec:
      containers:
      - name: clamav
        image: clamav/clamav:1.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3310
          name: api
          protocol: TCP
        # livenessProbe:
        #   exec:
        #     command:
        #     - /readyness.sh
        #   initialDelaySeconds: 20
        #   timeoutSeconds: 2
        resources:
          limits:
            memory: 1800Mi
          requests:
            memory: 1500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: clamav
  namespace: shared
spec:
  selector:
    app: clamav
  clusterIP: None
  ports:
  - name: zombie-port # Actually, we do not use this port but it is still needed to allow the service to receive TCP traffic.
    port: 3310
    targetPort: 3310