apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-single-az-delete
  annotations:
    storageclass.kubernetes.io/is-default-class: 'false'
  selfLink: /apis/storage.k8s.io/v1/storageclasses/gp3
allowVolumeExpansion: true
parameters:
  encrypted: 'true'
  fsType: ext4
  type: gp3
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: topology.ebs.csi.aws.com/zone
    values:
    - ca-central-1a